### ISSUE TITLE
Dodavanje git submodula

### ISSUE THREAD

**Issue by the-oneyouknow** [studosi/FER#2]
Moj prijedlog je da se dodaju git submoduli u repozitorij kao poveznice na repozitorije pojedinih predmeta.\
Možda bi se onda predmeti mogli svrstati po semestrima ili na već neki drugi način. Mislim da je ok da popis predmeta stoji u readme datoteci, ali bi bilo lijepo da još malo sredimo ovaj glavni repozitorij.\
Mogu pokušati to organizirati ako se @studosi i @studosi-fer (ne znam vodi li ta 2 accounta ista osoba) slažu, ili ako imate neke bolje ideje, slobodno :)

**Comment by studosi** [comment]
Bilo se razmišljalo o ovome, ali kako sustav integracije u forum koji je u planu ovakvo nešto ne treba, a kako bi submoduli zakomplicirali preuzimanje repozitorija, nije u planu.

Bilo bi to recimo korisno kad bi netko htio iz svojeg gita priložiti svoj rad i onda se to može povlačiti direktno kad se ažurira, ali u sustavu materijala ne žele se nikakvi dependencyji nego centraliziran sustav.

Problemi sa sortiranjem po semestrima su dinamičke prirode, i sukladno tome bit će rješeni na dinamički način kroz tu forumsku integraciju. Takva rješenja git baš ne omogućava (tj. nije osmišljen za takve probleme).
